import type { MetricDefinition } from '../core/types.js';

/**
 * The 7 launch metrics.
 *
 * Selection criteria:
 * - Used by real analysts
 * - Appears consistently across companies
 * - Stresses XBRL correctness
 * - Has interpretive value
 *
 * XBRL concepts are ordered by priority (try first = priority 1).
 * Multiple concepts exist because SEC taxonomy evolves and companies
 * sometimes use different tags for the same economic meaning.
 */

export const METRIC_DEFINITIONS: MetricDefinition[] = [
  {
    id: 'revenue',
    display_name: 'Revenue',
    description: 'Total revenue / net sales for the period',
    accounting_framework: 'US-GAAP',
    statement_type: 'income_statement',
    xbrl_concepts: [
      { taxonomy: 'us-gaap', concept: 'RevenueFromContractWithCustomerExcludingAssessedTax', valid_from: '2018-01-01', valid_to: null, priority: 1 },
      { taxonomy: 'us-gaap', concept: 'Revenues', valid_from: null, valid_to: null, priority: 2 },
      { taxonomy: 'us-gaap', concept: 'SalesRevenueNet', valid_from: null, valid_to: '2018-12-31', priority: 3 },
      { taxonomy: 'us-gaap', concept: 'RevenueFromContractWithCustomerIncludingAssessedTax', valid_from: '2018-01-01', valid_to: null, priority: 4 },
    ],
    unit_type: 'currency',
    aggregation: 'sum',
    version: 1,
    introduced_on: '2025-01-01',
    deprecated_on: null,
  },
  {
    id: 'net_income',
    display_name: 'Net Income',
    description: 'Net income attributable to the company (GAAP)',
    accounting_framework: 'US-GAAP',
    statement_type: 'income_statement',
    xbrl_concepts: [
      { taxonomy: 'us-gaap', concept: 'NetIncomeLoss', valid_from: null, valid_to: null, priority: 1 },
      { taxonomy: 'us-gaap', concept: 'ProfitLoss', valid_from: null, valid_to: null, priority: 2 },
      { taxonomy: 'us-gaap', concept: 'NetIncomeLossAvailableToCommonStockholdersBasic', valid_from: null, valid_to: null, priority: 3 },
    ],
    unit_type: 'currency',
    aggregation: 'sum',
    version: 1,
    introduced_on: '2025-01-01',
    deprecated_on: null,
  },
  {
    id: 'operating_cash_flow',
    display_name: 'Operating Cash Flow',
    description: 'Net cash provided by operating activities',
    accounting_framework: 'US-GAAP',
    statement_type: 'cash_flow',
    xbrl_concepts: [
      { taxonomy: 'us-gaap', concept: 'NetCashProvidedByUsedInOperatingActivities', valid_from: null, valid_to: null, priority: 1 },
      { taxonomy: 'us-gaap', concept: 'NetCashProvidedByUsedInOperatingActivitiesContinuingOperations', valid_from: null, valid_to: null, priority: 2 },
    ],
    unit_type: 'currency',
    aggregation: 'sum',
    version: 1,
    introduced_on: '2025-01-01',
    deprecated_on: null,
  },
  {
    id: 'capex',
    display_name: 'Capital Expenditures',
    description: 'Payments for acquisition of property, plant, and equipment',
    accounting_framework: 'US-GAAP',
    statement_type: 'cash_flow',
    xbrl_concepts: [
      { taxonomy: 'us-gaap', concept: 'PaymentsToAcquirePropertyPlantAndEquipment', valid_from: null, valid_to: null, priority: 1 },
      { taxonomy: 'us-gaap', concept: 'PaymentsToAcquireProductiveAssets', valid_from: null, valid_to: null, priority: 2 },
      { taxonomy: 'us-gaap', concept: 'CapitalExpendituresIncurredButNotYetPaid', valid_from: null, valid_to: null, priority: 3 },
    ],
    unit_type: 'currency',
    aggregation: 'sum',
    version: 1,
    introduced_on: '2025-01-01',
    deprecated_on: null,
  },
  {
    id: 'rd_expense',
    display_name: 'Research & Development Expense',
    description: 'Total research and development costs for the period',
    accounting_framework: 'US-GAAP',
    statement_type: 'income_statement',
    xbrl_concepts: [
      { taxonomy: 'us-gaap', concept: 'ResearchAndDevelopmentExpense', valid_from: null, valid_to: null, priority: 1 },
      { taxonomy: 'us-gaap', concept: 'ResearchAndDevelopmentExpenseExcludingAcquiredInProcessCost', valid_from: null, valid_to: null, priority: 2 },
    ],
    unit_type: 'currency',
    aggregation: 'sum',
    version: 1,
    introduced_on: '2025-01-01',
    deprecated_on: null,
  },
  {
    id: 'sbc',
    display_name: 'Stock-Based Compensation',
    description: 'Share-based / stock-based compensation expense',
    accounting_framework: 'US-GAAP',
    statement_type: 'cash_flow',
    xbrl_concepts: [
      { taxonomy: 'us-gaap', concept: 'ShareBasedCompensation', valid_from: null, valid_to: null, priority: 1 },
      { taxonomy: 'us-gaap', concept: 'AllocatedShareBasedCompensationExpense', valid_from: null, valid_to: null, priority: 2 },
      { taxonomy: 'us-gaap', concept: 'EmployeeBenefitsAndShareBasedCompensation', valid_from: null, valid_to: null, priority: 3 },
    ],
    unit_type: 'currency',
    aggregation: 'sum',
    version: 1,
    introduced_on: '2025-01-01',
    deprecated_on: null,
  },
  {
    id: 'total_debt',
    display_name: 'Total Debt',
    description: 'Total short-term and long-term debt',
    accounting_framework: 'US-GAAP',
    statement_type: 'balance_sheet',
    xbrl_concepts: [
      { taxonomy: 'us-gaap', concept: 'LongTermDebtAndCapitalLeaseObligations', valid_from: null, valid_to: null, priority: 1 },
      { taxonomy: 'us-gaap', concept: 'LongTermDebt', valid_from: null, valid_to: null, priority: 2 },
      { taxonomy: 'us-gaap', concept: 'DebtAndCapitalLeaseObligations', valid_from: null, valid_to: null, priority: 3 },
      { taxonomy: 'us-gaap', concept: 'LongTermDebtNoncurrent', valid_from: null, valid_to: null, priority: 4 },
    ],
    unit_type: 'currency',
    aggregation: 'end_of_period',
    version: 1,
    introduced_on: '2025-01-01',
    deprecated_on: null,
  },
  {
    id: 'operating_income',
    display_name: 'Operating Income',
    description: 'Income from operations before interest and taxes',
    accounting_framework: 'US-GAAP',
    statement_type: 'income_statement',
    xbrl_concepts: [
      { taxonomy: 'us-gaap', concept: 'OperatingIncomeLoss', valid_from: null, valid_to: null, priority: 1 },
      { taxonomy: 'us-gaap', concept: 'IncomeLossFromContinuingOperationsBeforeIncomeTaxesExtraordinaryItemsNoncontrollingInterest', valid_from: null, valid_to: null, priority: 2 },
    ],
    unit_type: 'currency',
    aggregation: 'sum',
    version: 1,
    introduced_on: '2025-01-01',
    deprecated_on: null,
  },
  {
    id: 'gross_profit',
    display_name: 'Gross Profit',
    description: 'Revenue minus cost of goods sold',
    accounting_framework: 'US-GAAP',
    statement_type: 'income_statement',
    xbrl_concepts: [
      { taxonomy: 'us-gaap', concept: 'GrossProfit', valid_from: null, valid_to: null, priority: 1 },
      { taxonomy: 'us-gaap', concept: 'CostOfRevenue', valid_from: null, valid_to: null, priority: 2 },
    ],
    unit_type: 'currency',
    aggregation: 'sum',
    version: 1,
    introduced_on: '2025-01-01',
    deprecated_on: null,
  },
  {
    id: 'eps',
    display_name: 'Earnings Per Share (Diluted)',
    description: 'Diluted earnings per share',
    accounting_framework: 'US-GAAP',
    statement_type: 'income_statement',
    xbrl_concepts: [
      { taxonomy: 'us-gaap', concept: 'EarningsPerShareDiluted', valid_from: null, valid_to: null, priority: 1 },
      { taxonomy: 'us-gaap', concept: 'EarningsPerShareBasic', valid_from: null, valid_to: null, priority: 2 },
    ],
    unit_type: 'ratio',
    aggregation: 'sum',
    version: 1,
    introduced_on: '2025-01-01',
    deprecated_on: null,
  },
  {
    id: 'total_assets',
    display_name: 'Total Assets',
    description: 'Total assets on the balance sheet',
    accounting_framework: 'US-GAAP',
    statement_type: 'balance_sheet',
    xbrl_concepts: [
      { taxonomy: 'us-gaap', concept: 'Assets', valid_from: null, valid_to: null, priority: 1 },
    ],
    unit_type: 'currency',
    aggregation: 'end_of_period',
    version: 1,
    introduced_on: '2025-01-01',
    deprecated_on: null,
  },
  {
    id: 'total_equity',
    display_name: "Shareholders' Equity",
    description: 'Total stockholders equity',
    accounting_framework: 'US-GAAP',
    statement_type: 'balance_sheet',
    xbrl_concepts: [
      { taxonomy: 'us-gaap', concept: 'StockholdersEquity', valid_from: null, valid_to: null, priority: 1 },
      { taxonomy: 'us-gaap', concept: 'StockholdersEquityIncludingPortionAttributableToNoncontrollingInterest', valid_from: null, valid_to: null, priority: 2 },
    ],
    unit_type: 'currency',
    aggregation: 'end_of_period',
    version: 1,
    introduced_on: '2025-01-01',
    deprecated_on: null,
  },
  {
    id: 'shares_outstanding',
    display_name: 'Shares Outstanding',
    description: 'Common shares outstanding (diluted)',
    accounting_framework: 'US-GAAP',
    statement_type: 'balance_sheet',
    xbrl_concepts: [
      { taxonomy: 'us-gaap', concept: 'CommonStockSharesOutstanding', valid_from: null, valid_to: null, priority: 1 },
      { taxonomy: 'us-gaap', concept: 'WeightedAverageNumberOfDilutedSharesOutstanding', valid_from: null, valid_to: null, priority: 2 },
      { taxonomy: 'us-gaap', concept: 'EntityCommonStockSharesOutstanding', valid_from: 'dei', valid_to: null, priority: 3 },
    ],
    unit_type: 'shares',
    aggregation: 'end_of_period',
    version: 1,
    introduced_on: '2025-01-01',
    deprecated_on: null,
  },
  // ── Phase 3 metrics ─────────────────────────────────────────────────
  {
    id: 'cost_of_revenue',
    display_name: 'Cost of Revenue',
    description: 'Cost of goods sold / cost of revenue',
    accounting_framework: 'US-GAAP',
    statement_type: 'income_statement',
    xbrl_concepts: [
      { taxonomy: 'us-gaap', concept: 'CostOfRevenue', valid_from: null, valid_to: null, priority: 1 },
      { taxonomy: 'us-gaap', concept: 'CostOfGoodsAndServicesSold', valid_from: null, valid_to: null, priority: 2 },
      { taxonomy: 'us-gaap', concept: 'CostOfGoodsSold', valid_from: null, valid_to: null, priority: 3 },
    ],
    unit_type: 'currency',
    aggregation: 'sum',
    version: 1,
    introduced_on: '2025-01-01',
    deprecated_on: null,
  },
  {
    id: 'sga_expense',
    display_name: 'SG&A Expense',
    description: 'Selling, general and administrative expense',
    accounting_framework: 'US-GAAP',
    statement_type: 'income_statement',
    xbrl_concepts: [
      { taxonomy: 'us-gaap', concept: 'SellingGeneralAndAdministrativeExpense', valid_from: null, valid_to: null, priority: 1 },
      { taxonomy: 'us-gaap', concept: 'GeneralAndAdministrativeExpense', valid_from: null, valid_to: null, priority: 2 },
      { taxonomy: 'us-gaap', concept: 'SellingAndMarketingExpense', valid_from: null, valid_to: null, priority: 3 },
    ],
    unit_type: 'currency',
    aggregation: 'sum',
    version: 1,
    introduced_on: '2025-01-01',
    deprecated_on: null,
  },
  {
    id: 'interest_expense',
    display_name: 'Interest Expense',
    description: 'Interest expense on debt obligations',
    accounting_framework: 'US-GAAP',
    statement_type: 'income_statement',
    xbrl_concepts: [
      { taxonomy: 'us-gaap', concept: 'InterestExpense', valid_from: null, valid_to: null, priority: 1 },
      { taxonomy: 'us-gaap', concept: 'InterestExpenseDebt', valid_from: null, valid_to: null, priority: 2 },
      { taxonomy: 'us-gaap', concept: 'InterestPaidNet', valid_from: null, valid_to: null, priority: 3 },
    ],
    unit_type: 'currency',
    aggregation: 'sum',
    version: 1,
    introduced_on: '2025-01-01',
    deprecated_on: null,
  },
  {
    id: 'income_tax',
    display_name: 'Income Tax Expense',
    description: 'Income tax expense (benefit)',
    accounting_framework: 'US-GAAP',
    statement_type: 'income_statement',
    xbrl_concepts: [
      { taxonomy: 'us-gaap', concept: 'IncomeTaxExpenseBenefit', valid_from: null, valid_to: null, priority: 1 },
      { taxonomy: 'us-gaap', concept: 'CurrentIncomeTaxExpenseBenefit', valid_from: null, valid_to: null, priority: 2 },
    ],
    unit_type: 'currency',
    aggregation: 'sum',
    version: 1,
    introduced_on: '2025-01-01',
    deprecated_on: null,
  },
  {
    id: 'dividends_per_share',
    display_name: 'Dividends Per Share',
    description: 'Cash dividends declared per common share',
    accounting_framework: 'US-GAAP',
    statement_type: 'income_statement',
    xbrl_concepts: [
      { taxonomy: 'us-gaap', concept: 'CommonStockDividendsPerShareDeclared', valid_from: null, valid_to: null, priority: 1 },
      { taxonomy: 'us-gaap', concept: 'CommonStockDividendsPerShareCashPaid', valid_from: null, valid_to: null, priority: 2 },
    ],
    unit_type: 'ratio',
    aggregation: 'sum',
    version: 1,
    introduced_on: '2025-01-01',
    deprecated_on: null,
  },
  {
    id: 'cash_and_equivalents',
    display_name: 'Cash & Equivalents',
    description: 'Cash, cash equivalents, and short-term investments',
    accounting_framework: 'US-GAAP',
    statement_type: 'balance_sheet',
    xbrl_concepts: [
      { taxonomy: 'us-gaap', concept: 'CashCashEquivalentsAndShortTermInvestments', valid_from: null, valid_to: null, priority: 1 },
      { taxonomy: 'us-gaap', concept: 'CashAndCashEquivalentsAtCarryingValue', valid_from: null, valid_to: null, priority: 2 },
      { taxonomy: 'us-gaap', concept: 'Cash', valid_from: null, valid_to: null, priority: 3 },
    ],
    unit_type: 'currency',
    aggregation: 'end_of_period',
    version: 1,
    introduced_on: '2025-01-01',
    deprecated_on: null,
  },
  {
    id: 'current_assets',
    display_name: 'Current Assets',
    description: 'Total current assets',
    accounting_framework: 'US-GAAP',
    statement_type: 'balance_sheet',
    xbrl_concepts: [
      { taxonomy: 'us-gaap', concept: 'AssetsCurrent', valid_from: null, valid_to: null, priority: 1 },
    ],
    unit_type: 'currency',
    aggregation: 'end_of_period',
    version: 1,
    introduced_on: '2025-01-01',
    deprecated_on: null,
  },
  {
    id: 'current_liabilities',
    display_name: 'Current Liabilities',
    description: 'Total current liabilities',
    accounting_framework: 'US-GAAP',
    statement_type: 'balance_sheet',
    xbrl_concepts: [
      { taxonomy: 'us-gaap', concept: 'LiabilitiesCurrent', valid_from: null, valid_to: null, priority: 1 },
    ],
    unit_type: 'currency',
    aggregation: 'end_of_period',
    version: 1,
    introduced_on: '2025-01-01',
    deprecated_on: null,
  },
  {
    id: 'goodwill',
    display_name: 'Goodwill',
    description: 'Goodwill from acquisitions',
    accounting_framework: 'US-GAAP',
    statement_type: 'balance_sheet',
    xbrl_concepts: [
      { taxonomy: 'us-gaap', concept: 'Goodwill', valid_from: null, valid_to: null, priority: 1 },
      { taxonomy: 'us-gaap', concept: 'GoodwillAndIntangibleAssetsNetExcludingGoodwill', valid_from: null, valid_to: null, priority: 2 },
    ],
    unit_type: 'currency',
    aggregation: 'end_of_period',
    version: 1,
    introduced_on: '2025-01-01',
    deprecated_on: null,
  },
  {
    id: 'total_liabilities',
    display_name: 'Total Liabilities',
    description: 'Total liabilities on the balance sheet',
    accounting_framework: 'US-GAAP',
    statement_type: 'balance_sheet',
    xbrl_concepts: [
      { taxonomy: 'us-gaap', concept: 'Liabilities', valid_from: null, valid_to: null, priority: 1 },
      { taxonomy: 'us-gaap', concept: 'LiabilitiesAndStockholdersEquity', valid_from: null, valid_to: null, priority: 2 },
    ],
    unit_type: 'currency',
    aggregation: 'end_of_period',
    version: 1,
    introduced_on: '2025-01-01',
    deprecated_on: null,
  },
];

/** Lookup a metric by ID */
export function getMetricDefinition(id: string): MetricDefinition | undefined {
  return METRIC_DEFINITIONS.find(m => m.id === id);
}

/** Lookup a metric by display name (case-insensitive, fuzzy) */
export function findMetricByName(name: string): MetricDefinition | undefined {
  const lower = name.toLowerCase();

  // Exact match on ID
  const byId = METRIC_DEFINITIONS.find(m => m.id === lower);
  if (byId) return byId;

  // Exact match on display name
  const byName = METRIC_DEFINITIONS.find(m => m.display_name.toLowerCase() === lower);
  if (byName) return byName;

  // Keyword matching
  const keywords: Record<string, string> = {
    'revenue': 'revenue',
    'sales': 'revenue',
    'top line': 'revenue',
    'net income': 'net_income',
    'profit': 'net_income',
    'earnings': 'net_income',
    'bottom line': 'net_income',
    'operating cash flow': 'operating_cash_flow',
    'cash from operations': 'operating_cash_flow',
    'ocf': 'operating_cash_flow',
    'capex': 'capex',
    'capital expenditure': 'capex',
    'capital spending': 'capex',
    'r&d': 'rd_expense',
    'r and d': 'rd_expense',
    'research and development': 'rd_expense',
    'research & development': 'rd_expense',
    'rd': 'rd_expense',
    'stock based compensation': 'sbc',
    'stock-based compensation': 'sbc',
    'share based compensation': 'sbc',
    'sbc': 'sbc',
    'total debt': 'total_debt',
    'debt': 'total_debt',
    'long term debt': 'total_debt',
    'operating income': 'operating_income',
    'operating profit': 'operating_income',
    'ebit': 'operating_income',
    'income from operations': 'operating_income',
    'gross profit': 'gross_profit',
    'gross margin': 'gross_profit',
    'eps': 'eps',
    'earnings per share': 'eps',
    'diluted eps': 'eps',
    'total assets': 'total_assets',
    'assets': 'total_assets',
    'equity': 'total_equity',
    'stockholders equity': 'total_equity',
    'shareholders equity': 'total_equity',
    'book value': 'total_equity',
    'shares outstanding': 'shares_outstanding',
    'share count': 'shares_outstanding',
    'diluted shares': 'shares_outstanding',
    'net margin': 'net_income',
    'income': 'net_income',
    'net profit': 'net_income',
    'net earnings': 'net_income',
    'capital expenditures': 'capex',
    'total revenue': 'revenue',
    'net sales': 'revenue',
    'gross margin ratio': 'gross_profit',
    'long-term debt': 'total_debt',
    'total stockholders equity': 'total_equity',
    'net worth': 'total_equity',
    'basic eps': 'eps',
    'cash flow from operations': 'operating_cash_flow',
    'cash flow operations': 'operating_cash_flow',
    'operational cash flow': 'operating_cash_flow',
    'compensation expense': 'sbc',
    'op income': 'operating_income',
    'common shares': 'shares_outstanding',
    'weighted average shares': 'shares_outstanding',
    // Phase 3 metrics
    'cost of revenue': 'cost_of_revenue',
    'cost of goods sold': 'cost_of_revenue',
    'cost of goods': 'cost_of_revenue',
    'cost of sales': 'cost_of_revenue',
    'cogs': 'cost_of_revenue',
    'sga': 'sga_expense',
    'sg&a': 'sga_expense',
    'selling general and administrative': 'sga_expense',
    'selling general': 'sga_expense',
    'admin expense': 'sga_expense',
    'interest expense': 'interest_expense',
    'interest cost': 'interest_expense',
    'interest paid': 'interest_expense',
    'income tax': 'income_tax',
    'tax expense': 'income_tax',
    'income taxes': 'income_tax',
    'provision for income taxes': 'income_tax',
    'dividends per share': 'dividends_per_share',
    'dividend per share': 'dividends_per_share',
    'dps': 'dividends_per_share',
    'dividends': 'dividends_per_share',
    'dividend': 'dividends_per_share',
    'cash and equivalents': 'cash_and_equivalents',
    'cash & equivalents': 'cash_and_equivalents',
    'cash on hand': 'cash_and_equivalents',
    'cash position': 'cash_and_equivalents',
    'cash': 'cash_and_equivalents',
    'current assets': 'current_assets',
    'current liabilities': 'current_liabilities',
    'goodwill': 'goodwill',
    'total liabilities': 'total_liabilities',
    'liabilities': 'total_liabilities',
  };

  // Sort by keyword length descending so longer matches take precedence
  // (e.g., "gross profit" matches before "profit")
  const sortedKeywords = Object.entries(keywords).sort((a, b) => b[0].length - a[0].length);
  for (const [keyword, metricId] of sortedKeywords) {
    if (lower.includes(keyword)) {
      return METRIC_DEFINITIONS.find(m => m.id === metricId);
    }
  }

  return undefined;
}
